# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Mahmoud Shrawy
#
# Rebuilds the sample workbooks in tests/samples, using Excel itself.
#
# Run it from a machine that has Excel installed:
#
#     powershell -ExecutionPolicy Bypass -File tests\make_samples.ps1
#
# The samples are checked into the repository, so the test suite runs
# without Excel and without running this. It exists for when a new case
# needs adding, and to record exactly how the existing files were made.
#
# Excel, not this program, has to write them. A workbook generated by our
# own code would only prove that the reader agrees with the writer; what
# actually breaks a reader is what Excel really does -- keeping text in a
# shared table, keeping a date as a number with a format beside it,
# leaving out the cells of empty columns, and turning 01001234567 into
# 1001234567 the moment a cell is not formatted as text.

$ErrorActionPreference = "Stop"
$dir = Join-Path $PSScriptRoot "samples"
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir | Out-Null }

$x = New-Object -ComObject Excel.Application
$x.Visible = $false
$x.DisplayAlerts = $false

# ---- 1. a real institutional roster: letterhead, then the headings ----
$wb = $x.Workbooks.Add(); $ws = $wb.Worksheets.Item(1); $ws.Name = "الكشف"
$ws.Range("A1:G1").Merge()
$ws.Cells.Item(1,1) = "مدرسة النيل الابتدائية الرسمية للغات"
$ws.Cells.Item(2,1) = "كشف بيانات أولياء الأمور - العام الدراسي 2025/2026"
$h = @("م","اسم الطالب","الصف","رقم ولي الأمر","البريد الإلكتروني","محل الإقامة","ملاحظات")
for ($i=0; $i -lt $h.Count; $i++) { $ws.Cells.Item(4, $i+1) = $h[$i] }
$names = @("أحمد محمود سيد","سارة خالد إبراهيم","محمد عبد الرحمن علي","نور الدين حسن",
           "مريم أشرف فاروق","يوسف طارق زغلول","فاطمة الزهراء محمد","عمر صلاح الدين",
           "ليلى مصطفى النجار","خالد سعيد المنشاوي")
$grades = @("الصف الأول","الصف الثاني","الصف الأول","الصف الثالث","الصف الثاني",
            "الصف الأول","الصف الثالث","الصف الثاني","الصف الأول","الصف الثالث")
for ($i=0; $i -lt 10; $i++) {
  $r = $i + 5
  $ws.Cells.Item($r,1) = $i + 1
  $ws.Cells.Item($r,2) = $names[$i]
  $ws.Cells.Item($r,3) = $grades[$i]
  # Left in the default format on purpose: this is the column that loses
  # its leading zero, which is the whole reason the reader needs a country.
  $ws.Cells.Item($r,4) = "0100" + (1234567 + $i * 111)
  $ws.Cells.Item($r,5) = "parent" + ($i+1) + "@example.com"
  $ws.Cells.Item($r,6) = "القاهرة - مدينة نصر"
}
$ws.Cells.Item(7,7) = "ولي الأمر يفضل التواصل مساءً"
$wb.SaveAs((Join-Path $dir "school_roster.xlsx"), 51); $wb.Close($false)

# ---- 2. one number written every way a person might write it ----
$wb = $x.Workbooks.Add(); $ws = $wb.Worksheets.Item(1); $ws.Name = "الأرقام"
$h2 = @("الاسم","رقم نصي","رقم رقمي","رقم دولي","أرقام هندية","رقم بمسافات","رقم بشرطات")
for ($i=0; $i -lt $h2.Count; $i++) { $ws.Cells.Item(1, $i+1) = $h2[$i] }
$ws.Columns.Item(2).NumberFormat = "@"
$ws.Columns.Item(4).NumberFormat = "@"
$ws.Columns.Item(5).NumberFormat = "@"
$rows = @(
  @("منى إبراهيم","01001234567","01001234567","+201001234567","٠١٠٠١٢٣٤٥٦٧","010 012 34567","0100-123-4567"),
  @("حسن علي","01115556666","01115556666","00201115556666","٠١١١٥٥٥٦٦٦٦","011 155 56666","0111-555-6666"),
  @("عبير سمير","0223334444","0223334444","+20223334444","٠٢٢٣٣٣٤٤٤٤","022 333 4444","022-333-4444")
)
for ($i=0; $i -lt $rows.Count; $i++) {
  for ($j=0; $j -lt 7; $j++) { $ws.Cells.Item($i+2, $j+1) = $rows[$i][$j] }
}
$wb.SaveAs((Join-Path $dir "phone_formats.xlsx"), 51); $wb.Close($false)

# ---- 3. several tabs, with the contacts on the second ----
$wb = $x.Workbooks.Add()
while ($wb.Worksheets.Count -lt 3) { $wb.Worksheets.Add() | Out-Null }
$s1 = $wb.Worksheets.Item(1); $s1.Name = "تعليمات"
$s1.Cells.Item(1,1) = "يرجى عدم التعديل على هذه الورقة"
$s1.Cells.Item(2,1) = "البيانات في ورقة جهات الاتصال"
$s2 = $wb.Worksheets.Item(2); $s2.Name = "جهات الاتصال"
$hh = @("الاسم الأول","اسم العائلة","الموبايل","البريد","الجهة")
for ($i=0; $i -lt $hh.Count; $i++) { $s2.Cells.Item(1, $i+1) = $hh[$i] }
$s2.Columns.Item(3).NumberFormat = "@"
$d = @(
  @("منى","إبراهيم","01001112222","mona@example.com","مدرسة النور"),
  @("طارق","عبد الحميد","01223334444","tarek@example.com","مدرسة النور"),
  @("هدى","السيد","01555556666","hoda@example.com","إدارة شرق")
)
for ($i=0; $i -lt $d.Count; $i++) { for ($j=0; $j -lt 5; $j++) { $s2.Cells.Item($i+2, $j+1) = $d[$i][$j] } }
$s3 = $wb.Worksheets.Item(3); $s3.Name = "إحصائيات"
$s3.Cells.Item(1,1) = "العدد"
$s3.Cells.Item(1,2).Formula = "=COUNTA('جهات الاتصال'!A2:A100)"
$wb.SaveAs((Join-Path $dir "multi_sheet.xlsx"), 51); $wb.Close($false)

# ---- 4. dates, formulas, errors, line breaks, prose ----
$wb = $x.Workbooks.Add(); $ws = $wb.Worksheets.Item(1); $ws.Name = "شاذ"
$hh2 = @("الاسم","تاريخ الميلاد","ملاحظات","نشط","الاسم الكامل","خطأ")
for ($i=0; $i -lt $hh2.Count; $i++) { $ws.Cells.Item(1, $i+1) = $hh2[$i] }
$ws.Cells.Item(2,1) = "سعاد"
$ws.Cells.Item(2,2) = [datetime]"2008-05-14"
$ws.Cells.Item(2,2).NumberFormat = "yyyy-mm-dd"
$ws.Cells.Item(2,3) = "سطر أول" + [char]10 + "سطر ثانٍ, وبه فاصلة"
$ws.Cells.Item(2,4) = $true
$ws.Cells.Item(2,5).Formula = '=A2 & " " & "الشريف"'
$ws.Cells.Item(2,6).Formula = "=NA()"
# Row 3 is left entirely empty, in the middle of the data.
$ws.Cells.Item(4,1) = "كريم"
$ws.Cells.Item(4,2) = [datetime]"1999-12-31"
$ws.Cells.Item(4,2).NumberFormat = "dd/mm/yyyy"
$ws.Cells.Item(4,3) = 'نص فيه "علامات اقتباس" وفاصلة، ونقطة.'
$ws.Cells.Item(4,4) = $false
$ws.Cells.Item(5,1) = "نص طويل جداً " * 40
$wb.SaveAs((Join-Path $dir "edge_cases.xlsx"), 51); $wb.Close($false)

# ---- 5. identity numbers, which must never be imported ----
$wb = $x.Workbooks.Add(); $ws = $wb.Worksheets.Item(1); $ws.Name = "بيانات"
$h5 = @("م","اسم ولي الأمر","الرقم القومي","رقم التواصل","بيانات إضافية","الصف")
for ($i=0; $i -lt $h5.Count; $i++) { $ws.Cells.Item(1, $i+1) = $h5[$i] }
$ws.Columns.Item(3).NumberFormat = "@"
$idNames = @("سمير عبد الله حسن","نادية فؤاد الشريف","رمضان علي محمود")
# Invented numbers, and invented in a way that matters. An Egyptian
# national ID carries a governorate code in its eighth and ninth digits,
# and every assigned code lies between 01 and 35, or is 88 for a birth
# abroad. These all use 00, which is assigned to nowhere. So they are
# still shaped like real numbers -- the detector has to catch them, which
# is the point of the file -- while being numbers that cannot belong to
# any living person. This repository is public; a fixture that happened
# to match a real citizen's identity number would be a bad thing to have
# published, and there is no reason to take the chance.
$ids = @("29805150012345","30112200012346","27703100012347")
# One column mixes identity numbers with ordinary text, so the value
# check is tested and not only the column heading.
$extra = @("28809090012341","ملاحظة عادية","29001010012342")
for ($i=0; $i -lt 3; $i++) {
  $ws.Cells.Item($i+2,1) = $i+1
  $ws.Cells.Item($i+2,2) = $idNames[$i]
  $ws.Cells.Item($i+2,3) = $ids[$i]
  $ws.Cells.Item($i+2,4) = "0100" + (5551234 + $i)
  $ws.Cells.Item($i+2,5) = $extra[$i]
  $ws.Cells.Item($i+2,6) = "الصف الأول"
}
$wb.SaveAs((Join-Path $dir "national_ids.xlsx"), 51); $wb.Close($false)

$x.Quit()
[System.Runtime.InteropServices.Marshal]::ReleaseComObject($x) | Out-Null

Get-ChildItem $dir -Filter *.xlsx | ForEach-Object {
  "{0,-24} {1,7} bytes" -f $_.Name, $_.Length
}
